### ISSUE TITLE
Error: App Not Setup. This app is still in development mode

### ISSUE THREAD

**Issue by Mo7mud** [ktiyaav/facebook-autoliker#1]
Hi,
Thank you for this great script.
When I try to authorize my account to get my access token I get this error:
Error: App Not Setup. This app is still in development mode, and you don't have access to it.....

How to solve this issue?

**Comment by shaktiraksel** [comment]
You need to setup a new app & copy client id and replace it in login.php file. After that replace the Token URL from index.php file.

If you don't know how to setup app, you can copy some other autoliker's app client id and link and use that in this script.

**Comment by Mo7mud** [comment]
Thank you very much
